/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Score } from './score';
import { Team } from './team';

export interface Match {
  id?: number;
  utcDate?: string;
  status?: string;
  matchday?: number;
  homeTeam?: Team;
  awayTeam?: Team;
  score?: Score;
}
