/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Competition } from './competition';
import { Filters } from './filters';
import { ResultSet } from './resultSet';
import { Match } from './match';


export interface MatchesResponse { 
    filters?: Filters;
    resultSet?: ResultSet;
    competition?: Competition;
    matches?: Array<Match>;
}

