/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScoreDetail } from './scoreDetail';

export interface Score {
  winner?: string;
  duration?: string;
  fullTime?: ScoreDetail;
  halfTime?: ScoreDetail;
}
